env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  sourceType: module
rules:
  no-console: 'off'
  quotes: 'off'
  semi:
  - error
  - never
